### ISSUE TITLE
Global Search Error - SuiteCRM 8 - Basic Search

### ISSUE THREAD

**Issue by nsarant** [salesagility/SuiteCRM-Core#115]
#### Issue

When using Global Search, there is error returned:
"An unknown error has occurred while performing the search. Contact an administrator if the problem persists. More information available in the logs."
#### Expected Behavior

It should either return results or return that there was no result at all.
#### Actual Behavior

On browser it returns the generic error 
"An unknown error has occurred while performing the search. Contact an administrator if the problem persists. More information available in the logs."
``` 
cat /var/www/html/SuiteCRM8/public/legacy/suitecrm.log
Mon Jun 20 19:11:03 2022 [49660][1][FATAL] [ERROR] [SearchThrowableHandler] An unknown error has occurred while performing the search.
Mon Jun 20 19:11:03 2022 [49660][1][FATAL] [ERROR] [SearchThrowableHandler] Error: Call to a member function getFocus() on string in /var/www/html/SuiteCRM8/public/legacy/lib/Search/SearchResults.php:220
Stack trace:
#0 /var/www/html/SuiteCRM8/public/legacy/lib/Search/SearchResults.php(179): SuiteCRM\Search\SearchResults->getRelatedId()
salesagility/SuiteCRM#1 /var/www/html/SuiteCRM8/public/legacy/lib/Search/SearchResults.php(162): SuiteCRM\Search\SearchResults->updateObjLinks()
salesagility/SuiteCRM#2 /var/www/html/SuiteCRM8/public/legacy/lib/Search/SearchResults.php(145): SuiteCRM\Search\SearchResults->updateFieldDefLinks()
salesagility/SuiteCRM#3 /var/www/html/SuiteCRM8/public/legacy/lib/Search/UI/SearchResultsController.php(142): SuiteCRM\Search\SearchResults->getHitsAsBeans()
salesagility/SuiteCRM#4 /var/www/html/SuiteCRM8/public/legacy/lib/Search/SearchEngine.php(102): SuiteCRM\Search\UI\SearchResultsController->display()
salesagility/SuiteCRM#5 /var/www/html/SuiteCRM8/public/legacy/lib/Search/SearchEngine.php(78): SuiteCRM\Search\SearchEngine->displayResults()
salesagility/SuiteCRM#6 /var/www/html/SuiteCRM8/public/legacy/lib/Search/SearchWrapper.php(88): SuiteCRM\Search\SearchEngine->searchAndDisplay()
salesagility/SuiteCRM#7 /var/www/html/SuiteCRM8/public/legacy/modules/Home/Search.php(53): SuiteCRM\Search\SearchWrapper::searchAndDisplay()
salesagility/SuiteCRM#8 /var/www/html/SuiteCRM8/public/legacy/modules/Home/UnifiedSearch.php(41): require_once('/var/www/html/S...')
salesagility/SuiteCRM#9 /var/www/html/SuiteCRM8/public/legacy/include/MVC/View/SugarView.php(798): include_once('/var/www/html/S...')
salesagility/SuiteCRM#10 /var/www/html/SuiteCRM8/public/legacy/include/MVC/View/views/view.classic.php(72): SugarView->includeClassicFile()
salesagility/SuiteCRM#11 /var/www/html/SuiteCRM8/public/legacy/include/MVC/View/SugarView.php(210): ViewClassic->display()
salesagility/SuiteCRM#12 /var/www/html/SuiteCRM8/public/legacy/include/MVC/Controller/SugarController.php(432): SugarView->process()
salesagility/SuiteCRM#13 /var/www/html/SuiteCRM8/public/legacy/include/MVC/Controller/SugarController.php(363): SugarController->processView()
salesagility/SuiteCRM#14 /var/www/html/SuiteCRM8/public/legacy/include/MVC/SugarApplication.php(101): SugarController->execute()
salesagility/SuiteCRM#15 /var/www/html/SuiteCRM8/public/legacy/index.php(55): SugarApplication->execute()
salesagility/SuiteCRM#16 {main}
``` 
#### Possible Fix

in file
```/var/www/html/[suite-crm-name]/public/legacy/lib/Search/SearchResults.php:211```
Replacing 
```if (isset($obj->$link))```
with
```if (isset($obj->$link) && method_exists($obj->$link, "getFocus"))```
seems to fix it.
#### Steps to Reproduce

1. Install SuiteCRM 8.1
2. Admin->Search Settings->Search Engine:Basic Search
3. Create a demo entry in a module that I am going to search
4. Search for the name - it must match. If it doesn't match it returns that there is no result (as expected). If it matches it returns the error.
#### Context

I feel this should be high priority since Global Search is basic functionality and (Ibelieve) the file affected is going to be replaced in case of an upgrade.
#### Your Environment

* SuiteCRM Version used: 8.1.0 
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox Version 101.0.1 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): Apache/2.4.37, MariaDB 10.6.8, PHP 7.4
* Operating System and version (e.g Ubuntu 16.04): AlmaLinux release 8.6 (Sky Tiger)

**Comment by johnM2401** [comment]
Hey there, 

I've given this a try on 8.1.2 and I'm afraid I'm not able to replicate

Do you know if this requires any specific data set?
(ie, Searching on Specific Fields / Modules)

Would you be able to give a quick example of a Search Term used, and on which Module, for us to compare results?

<br>

Also, do you have any sort of Security Groups / Roles set up around the modules that are searched on?
(Just want to try to rule this out)


Thanks for getting in touch!

**Comment by johnM2401** [comment]
Hey!

Thanks for getting in touch.

Closing due to inactivity.

After testing in 8.2.3, it appears to work as expected.

![image](https://user-images.githubusercontent.com/13675281/216647994-a5653b32-5d38-45ee-b22f-d0109bc3f2ca.png)
![image](https://user-images.githubusercontent.com/13675281/216648020-43eadc0d-c297-4d39-8f38-b96f18e9a254.png)

The search term used in Global Search is returning records, even when there is not a Full identical match.
For further partial matches, wildcards can be used:
![image](https://user-images.githubusercontent.com/13675281/216648139-023f5a17-dbe6-4a41-836b-1f27a7b087d4.png)


Please get in touch if you are still having Search issues, (or any other issues), with SuiteCRM8 and we can re-investigate.

Thanks!
