### ISSUE TITLE
(8.1.2) elastic:index not working

### ISSUE THREAD

**Issue by yazynin** [salesagility/SuiteCRM-Core#133]
elastic:index not working

#### Issue
```
root@3a4ec0245509:/bitnami/suitecrm# vendor/bin/robo elastic:index 0
PHP Warning:  Attempt to read property "app_list_strings.en_us" on null in /bitnami/suitecrm/public/legacy/include/SugarCache/SugarCache.php on line 211
PHP Fatal error:  Uncaught Error: Call to a member function set() on null in /bitnami/suitecrm/public/legacy/include/SugarCache/SugarCache.php:223
Stack trace:
#0 /bitnami/suitecrm/public/legacy/include/utils.php(1201): sugar_cache_put()
#1 /bitnami/suitecrm/public/legacy/lib/Robo/Traits/CliRunnerTrait.php(90): return_app_list_strings_language()
#2 /bitnami/suitecrm/public/legacy/lib/Robo/Plugin/Commands/ApiCommands.php(82): SuiteCRM\Robo\Plugin\Commands\ApiCommands->bootstrap()
#3 [internal function]: SuiteCRM\Robo\Plugin\Commands\ApiCommands->__construct()
#4 /bitnami/suitecrm/vendor/league/container/src/Definition/ClassDefinition.php(47): ReflectionClass->newInstanceArgs()
#5 /bitnami/suitecrm/vendor/league/container/src/Container.php(289): League\Container\Definition\ClassDefinition->build()
#6 /bitnami/suitecrm/vendor/league/container/src/Container.php(85): League\Container\Container->getFromThisContainer()
#7 /bitnami/suitecrm/vendor/consolidation/robo/src/Runner.php(380): League\Container\Container->get()
#8 /bitnami/suitecrm/vendor/consolidation/robo/src/Runner.php(342): Robo\Runner->instantiateCommandClass()
#9 /bitnami/suitecrm/vendor/consolidation/robo/src/Runner.php(315): Robo\Runner->registerCommandClass()
#10 /bitnami/suitecrm/vendor/consolidation/robo/src/Runner.php(276): Robo\Runner->registerCommandClasses()
#11 /bitnami/suitecrm/vendor/consolidation/robo/src/Runner.php(157): Robo\Runner->run()
#12 /bitnami/suitecrm/vendor/consolidation/robo/robo(48): Robo\Runner->execute()
#13 /bitnami/suitecrm/vendor/bin/robo(120): include('...')
#14 {main}
  thrown in /bitnami/suitecrm/public/legacy/include/SugarCache/SugarCache.php on line 223
ERROR: Uncaught Error: Call to a member function set() on null in /bitnami/suitecrm/public/legacy/include/SugarCache/SugarCache.php:223
Stack trace:
#0 /bitnami/suitecrm/public/legacy/include/utils.php(1201): sugar_cache_put()
#1 /bitnami/suitecrm/public/legacy/lib/Robo/Traits/CliRunnerTrait.php(90): return_app_list_strings_language()
#2 /bitnami/suitecrm/public/legacy/lib/Robo/Plugin/Commands/ApiCommands.php(82): SuiteCRM\Robo\Plugin\Commands\ApiCommands->bootstrap()
#3 [internal function]: SuiteCRM\Robo\Plugin\Commands\ApiCommands->__construct()
#4 /bitnami/suitecrm/vendor/league/container/src/Definition/ClassDefinition.php(47): ReflectionClass->newInstanceArgs()
#5 /bitnami/suitecrm/vendor/league/container/src/Container.php(289): League\Container\Definition\ClassDefinition->build()
#6 /bitnami/suitecrm/vendor/league/container/src/Container.php(85): League\Container\Container->getFromThisContainer()
#7 /bitnami/suitecrm/vendor/consolidation/robo/src/Runner.php(380): League\Container\Container->get()
#8 /bitnami/suitecrm/vendor/consolidation/robo/src/Runner.php(342): Robo\Runner->instantiateCommandClass()
#9 /bitnami/suitecrm/vendor/consolidation/robo/src/Runner.php(315): Robo\Runner->registerCommandClass()
#10 /bitnami/suitecrm/vendor/consolidation/robo/src/Runner.php(276): Robo\Runner->registerCommandClasses()
#11 /bitnami/suitecrm/vendor/consolidation/robo/src/Runner.php(157): Robo\Runner->run()
#12 /bitnami/suitecrm/vendor/consolidation/robo/robo(48): Robo\Runner->execute()
#13 /bitnami/suitecrm/vendor/bin/robo(120): include('...')
#14 {main}
  thrown
in /bitnami/suitecrm/public/legacy/include/SugarCache/SugarCache.php:223
```
#### Steps to Reproduce
1. vendor/bin/robo elastic:index 0

#### Your Environment

* SuiteCRM Version used: 8.1.2 
* Environment name and version (e.g. MySQL, PHP 7): mysql, php 8.0.19

**Comment by ryanjkemper** [comment]
I'm also having this issue, using the Bitnami docker image.  I had deleted everything in the cache folder, and am now trying to create a new user using a robo script.  Getting this exact same error and stack trace.
