### ISSUE TITLE
IMAP INBOUND EMAIL error - ver 8.2.2

### ISSUE THREAD

**Issue by smokenik** [salesagility/SuiteCRM-Core#186]
#### Issue
I have done fresh install 8.2.1 same LAMP (php v8.0 maria db 10.5.18) and I can access:
#/inbound-email/index
in 8.2.2 I cannot because of error: "Error occurred while fetching metadata"

Also notice in “email settings” for users is not visible in “modal window” the tab [Mail Account] . Probably something goes wrong in the 8.2.2 ver

#### Expected Behavior
display Email inbox like 8.2.1 ver
display in “email settings” for users in “modal window” the tab [Mail Account] to set inbox imap
#### Actual Behavior
#/inbound-email/index
in 8.2.2 ko because of error: "Error occurred while fetching metadata"
not display in “email settings” for users in “modal window” the tab [Mail Account] to set inbox imap

#### Possible Fix
?
#### Steps to Reproduce
Fresh install LAMP (docker apache buster) php 8.0.26 maria db 10.5 suitecrm 8.2.2 and click where things go wrong instead of same lamp but 8.2.1 where things go fine

#### Your Environment

Dockerized LAMP php 8.0.26 (php:8.0.26-apache-buster) + mariadb 10.5

but I have tested with all php ver 7.2,7.3,7.4    and same error!

**Comment by clemente-raposo** [comment]
Hi @smokenik, 

Thank you for your feedback.

If you have the time and the patience, could you try the following please:

- on .env.local change APP_ENV to `qa`
- run `php bin/console cache:clear
- go to the app
- Open the dev tools of the browser
- Clear the network tab
- Try opening the InboundEmails again. You should get same error.
- On the dev tools go to the network tab
- on the network tab you might find:
    - a request with an error 500, 403, etc
    - on one of the `grahpql` calls there might be an error on the response body.

If you find one of these errors on the network tab, could you send it please? this information would help use identify the problem.

**Comment by smokenik** [comment]
in network tab nothing, but...

this is console in dev tools chrome:


main-es2015.0c8558d916186568bdcc.js:1 Unsatisfied version 0 of shared singleton module luxon (required =3.0.0)
t @ main-es2015.0c8558d916186568bdcc.js:1
dist_core___ivy_ngcc___fesm2015_core_js-_92d41-es2015.85e46b4b7cc754f175df.js:32 Login success
​ JQMIGRATE: Migrate is installed, version 3.4.0
​ JQMIGRATE: Migrate is installed, version 3.4.0
inlineEditing.js:52 Uncaught ReferenceError: action_sugar_grp1 is not defined
    at inlineEditing.js:52:12
​ JQMIGRATE: Migrate is installed, version 3.4.0
/legacy/index.php?module=Users&action=EditView&record=1:1 [DOM] Found 2 elements with non-unique id #assigned_user_id: (More info: https://goo.gl/9p2vKq) %o %o
/legacy/index.php?module=Users&action=EditView&record=1:1 [DOM] Found 2 elements with non-unique id #assigned_user_name: (More info: https://goo.gl/9p2vKq) %o %o
/legacy/index.php?module=Users&action=EditView&record=1:1 [DOM] Found 2 elements with non-unique id #group_id: (More info: https://goo.gl/9p2vKq) %o %o
/legacy/index.php?module=Users&action=EditView&record=1:1 [DOM] Found 2 elements with non-unique id #outboundtest_from_address: (More info: https://goo.gl/9p2vKq) %o %o
/legacy/index.php?module=Users&action=EditView&record=1:1 [DOM] Found 2 elements with non-unique id #record: (More info: https://goo.gl/9p2vKq) %o %o
2​ JQMIGRATE: Migrate is installed, version 3.4.0
main-es2015.0c8558d916186568bdcc.js:1 Unsatisfied version 0 of shared singleton module luxon (required =3.0.0)
t @ main-es2015.0c8558d916186568bdcc.js:1
polyfills-es2015.e450e5585fc067c2eadd.js:1 Unhandled Promise rejection: Cannot read properties of undefined (reading 'moduleMetadata') ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read properties of undefined (reading 'moduleMetadata')
    at o.project (dist_core___ivy_ngcc___fesm2015_core_js-_92d41-es2015.85e46b4b7cc754f175df.js:32:14075)
    at o._next (node_modules_rxjs__esm2015_operators_index_js-es2015.8f2820c8ba6a75453b5e.js:1:24803)
    at o.next (node_modules_rxjs__esm2015_operators_index_js-es2015.8f2820c8ba6a75453b5e.js:1:8495)
    at node_modules_apollo-angular_fesm2015_ngApollo_js-_0ddc0-es2015.31fc3a06fac668918939.js:1:76264
    at u.invoke (polyfills-es2015.e450e5585fc067c2eadd.js:1:7152)
    at Object.onInvoke (node_modules_angular_core_fesm2015_core_js-es2015.e67882692b6d3d658f6b.js:1:198185)
    at u.invoke (polyfills-es2015.e450e5585fc067c2eadd.js:1:7092)
    at t.run (polyfills-es2015.e450e5585fc067c2eadd.js:1:2551)
    at polyfills-es2015.e450e5585fc067c2eadd.js:1:17235
    at u.invokeTask (polyfills-es2015.e450e5585fc067c2eadd.js:1:7770) TypeError: Cannot read properties of undefined (reading 'moduleMetadata')
    at o.project (http://suitecrm.vpn.hivesrl.net/dist/dist_core___ivy_ngcc___fesm2015_core_js-_92d41-es2015.85e46b4b7cc754f175df.js:32:14075)
    at o._next (http://suitecrm.vpn.hivesrl.net/dist/node_modules_rxjs__esm2015_operators_index_js-es2015.8f2820c8ba6a75453b5e.js:1:24803)
    at o.next (http://suitecrm.vpn.hivesrl.net/dist/node_modules_rxjs__esm2015_operators_index_js-es2015.8f2820c8ba6a75453b5e.js:1:8495)
    at http://suitecrm.vpn.hivesrl.net/dist/node_modules_apollo-angular_fesm2015_ngApollo_js-_0ddc0-es2015.31fc3a06fac668918939.js:1:76264
    at u.invoke (http://suitecrm.vpn.hivesrl.net/dist/polyfills-es2015.e450e5585fc067c2eadd.js:1:7152)
    at Object.onInvoke (http://suitecrm.vpn.hivesrl.net/dist/node_modules_angular_core_fesm2015_core_js-es2015.e67882692b6d3d658f6b.js:1:198185)
    at u.invoke (http://suitecrm.vpn.hivesrl.net/dist/polyfills-es2015.e450e5585fc067c2eadd.js:1:7092)
    at t.run (http://suitecrm.vpn.hivesrl.net/dist/polyfills-es2015.e450e5585fc067c2eadd.js:1:2551)
    at http://suitecrm.vpn.hivesrl.net/dist/polyfills-es2015.e450e5585fc067c2eadd.js:1:17235
    at u.invokeTask (http://suitecrm.vpn.hivesrl.net/dist/polyfills-es2015.e450e5585fc067c2eadd.js:1:7770)
n.onUnhandledError @ polyfills-es2015.e450e5585fc067c2eadd.js:1
node_modules_angular_core_fesm2015_core_js-es2015.e67882692b6d3d658f6b.js:1 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'moduleMetadata')
TypeError: Cannot read properties of undefined (reading 'moduleMetadata')
    at o.project (dist_core___ivy_ngcc___fesm2015_core_js-_92d41-es2015.85e46b4b7cc754f175df.js:32:14075)
    at o._next (node_modules_rxjs__esm2015_operators_index_js-es2015.8f2820c8ba6a75453b5e.js:1:24803)
    at o.next (node_modules_rxjs__esm2015_operators_index_js-es2015.8f2820c8ba6a75453b5e.js:1:8495)
    at node_modules_apollo-angular_fesm2015_ngApollo_js-_0ddc0-es2015.31fc3a06fac668918939.js:1:76264
    at u.invoke (polyfills-es2015.e450e5585fc067c2eadd.js:1:7152)
    at Object.onInvoke (node_modules_angular_core_fesm2015_core_js-es2015.e67882692b6d3d658f6b.js:1:198185)
    at u.invoke (polyfills-es2015.e450e5585fc067c2eadd.js:1:7092)
    at t.run (polyfills-es2015.e450e5585fc067c2eadd.js:1:2551)
    at polyfills-es2015.e450e5585fc067c2eadd.js:1:17235
    at u.invokeTask (polyfills-es2015.e450e5585fc067c2eadd.js:1:7770)
    at w (polyfills-es2015.e450e5585fc067c2eadd.js:1:16429)
    at w (polyfills-es2015.e450e5585fc067c2eadd.js:1:15965)
    at polyfills-es2015.e450e5585fc067c2eadd.js:1:17272
    at u.invokeTask (polyfills-es2015.e450e5585fc067c2eadd.js:1:7770)
    at Object.onInvokeTask (node_modules_angular_core_fesm2015_core_js-es2015.e67882692b6d3d658f6b.js:1:198001)
    at u.invokeTask (polyfills-es2015.e450e5585fc067c2eadd.js:1:7691)
    at t.runTask (polyfills-es2015.e450e5585fc067c2eadd.js:1:3166)
    at b (polyfills-es2015.e450e5585fc067c2eadd.js:1:9764)
    at l.invokeTask [as invoke] (polyfills-es2015.e450e5585fc067c2eadd.js:1:8849)
    at m (polyfills-es2015.e450e5585fc067c2eadd.js:1:20635)
ni @ node_modules_angular_core_fesm2015_core_js-es2015.e67882692b6d3d658f6b.js:1
Impossibile caricare la mappa di origine in DevTools: Impossibile caricare il contenuto per http://suitecrm.vpn.hivesrl.net/jquery.qtip.min.js.map: Fetch through target failed: Frame not found; Fallback: Errore HTTP: codice di stato 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE.

**Comment by smokenik** [comment]
{@context: "/api/contexts/Error", @type: "hydra:Error", hydra:title: "An error occurred",…}
@context
: 
"/api/contexts/Error"
@type
: 
"hydra:Error"
hydra:description
: 
"Failed to start the session because headers have already been sent by \"/var/www/html/public/legacy/modules/InboundEmail/metadata/editviewdefs.php\" at line 1."
hydra:title
: 
"An error occurred"
trace
: 
[{namespace: "", short_class: "", class: "", type: "", function: "",…},…]

**Comment by inlog** [comment]
Inbound Email Accounts — Error occurred while fetching metadata

nothing is added to the logs

In console:

ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading ‘moduleMetadata’)
TypeError: Cannot read properties of undefined (reading ‘moduleMetadata’)
at o.project (dist_core___ivy_ngcc___fesm2015_core_js-_92d41-es2015.85e46b4b7cc754f175df.js:32:14075)
at o._next (node_modules_rxjs__esm2015_operators_index_js-es2015.8f2820c8ba6a75453b5e.js:1:24803)
at o.next (node_modules_rxjs__esm2015_operators_index_js-es2015.8f2820c8ba6a75453b5e.js:1:8495)
at node_modules_apollo-angular_fesm2015_ngApollo_js-_0ddc0-es2015.31fc3a06fac668918939.js:1:76264
at u.invoke (polyfills-es2015.45bb605d0a332f4c1a8e.js:1:7152)
at Object.onInvoke (node_modules_angular_core_fesm2015_core_js-es2015.e67882692b6d3d658f6b.js:1:198185)
at u.invoke (polyfills-es2015.45bb605d0a332f4c1a8e.js:1:7092)
at t.run (polyfills-es2015.45bb605d0a332f4c1a8e.js:1:2551)
at polyfills-es2015.45bb605d0a332f4c1a8e.js:1:17235
at u.invokeTask (polyfills-es2015.45bb605d0a332f4c1a8e.js:1:7770)
at w (polyfills-es2015.45bb605d0a332f4c1a8e.js:1:16429)
at w (polyfills-es2015.45bb605d0a332f4c1a8e.js:1:15965)
at polyfills-es2015.45bb605d0a332f4c1a8e.js:1:17272
at u.invokeTask (polyfills-es2015.45bb605d0a332f4c1a8e.js:1:7770)
at Object.onInvokeTask (node_modules_angular_core_fesm2015_core_js-es2015.e67882692b6d3d658f6b.js:1:198001)
at u.invokeTask (polyfills-es2015.45bb605d0a332f4c1a8e.js:1:7691)
at t.runTask (polyfills-es2015.45bb605d0a332f4c1a8e.js:1:3166)
at b (polyfills-es2015.45bb605d0a332f4c1a8e.js:1:9764)
at l.invokeTask [as invoke] (polyfills-es2015.45bb605d0a332f4c1a8e.js:1:8849)
at m (polyfills-es2015.45bb605d0a332f4c1a8e.js:1:20635)

**Comment by ArchGroot** [comment]
Something similar here. I can't access Inbound Email settings, receiving in page the pink error "Error occurred while fetching metadata" . 
Version 8.2.3, installed by Softaculous on a webserver, PHP 7.4 , MySql 5.7
[Error fetching metadata.txt](https://github.com/salesagility/SuiteCRM-Core/files/10725710/Error.fetching.metadata.txt)

**Comment by hans861** [comment]
Hi, i have similar error "Error occurred while fetching metadata".
My configuration is:
suiteCRM ver. 8.2.3

Server configuration:
cPanel Versión | 102.0 (build 30)
Softaculous ver. 5.9.6 
Versión Apache | 2.4.55
Versión PHP | 8.1.16
Versión MySQL | 5.7.23-23
Arquitectura | x86_64
Versión Perl | 5.16.3

**Comment by pgorod** [comment]
@clemente-raposo it appears this is caused by a few extra spaces accidentally added in the beginning of this file, before the `<?php` tag.

https://github.com/salesagility/SuiteCRM-Core/blame/hotfix/public/legacy/modules/InboundEmail/metadata/editviewdefs.php

**Comment by peja-dev** [comment]
@pgorod thanks for adding my comment in opened issue. br

**Comment by pgorod** [comment]
> @pgorod thanks for adding my comment in opened issue. br

@peja-dev Thank _you_ for debugging the issue and finding out the cause :-)

(I think Suitebot is asleep, but when I posted the comment on the Forums linking to this issue, the bot was supposed to add a reference here so people could go and read about it and see [where the fix was coming from](https://community.suitecrm.com/t/inbound-email-error-fresh-install-latest-suitecrm8/87485/11?u=pgr))

**Comment by hans861** [comment]
thanks @pgorod
I made the change in the file (remove empty spaces ) and it works.

**Comment by ericgopak** [comment]
thanks @pgorod
this was an issue for me with SuiteCRM 8.2

**Comment by johnM2401** [comment]
Hey all!
Thank you for raising this, and thank you to everyone for your further discussions, diagnosis and fix-finding.

I'm going to close this issue off for now, as the issue was resolved in the main branch with the PR: https://github.com/salesagility/SuiteCRM/pull/10300

However, if any of your are seeing this issue still, in more recent versions, please don't hesitate to get in touch.

Thank you all again for your contributions to the project!
