### ISSUE TITLE
Error running ElasticSearch indexing

### ISSUE THREAD

**Issue by m8nky** [salesagility/SuiteCRM-Core#220]
#### Issue
ElasticSearch trigger manual indexing via web portal does not work.

Steps to reproduce:
1. Activated the ElasticSearch module, test connection works.
2. Triggered 'Schedule Full Indexing', job gets added.
3. When the cron runs a minute later, it throws an error and the job gets deleted:

```
PHP Fatal error:  Uncaught TypeError: json_decode(): Argument #1 ($json) must be of type string, SchedulersJob given in /var/www/html/public/legacy/modules/Schedulers/_AddJobsHere.php:837
Stack trace:
#0 /var/www/html/public/legacy/modules/Schedulers/_AddJobsHere.php(837): json_decode()
#1 /var/www/html/public/legacy/modules/SchedulersJobs/SchedulersJob.php(528): runElasticSearchIndexerScheduler()
#2 /var/www/html/public/legacy/include/SugarQueue/SugarCronJobs.php(191): SchedulersJob->runJob()
```

Checking the affected code line, it looks pretty straightforward but expects a deserializable parameter, instead of the Job itself.

```php
function runElasticSearchIndexerScheduler($data)
{
    return \SuiteCRM\Search\ElasticSearch\ElasticSearchIndexer::schedulerJob(json_decode($data));
}
```

#### Expected Behavior

The indexer runs without errors. Afterwards the search should show results.

#### Actual Behavior

The indexer job does not run. And when searching, the log states a 404, that the index has not been found:
```
Tue Feb 21 19:53:26 2023 [63][1][FATAL] [ERROR] [SearchThrowableHandler] Elasticsearch\Common\Exceptions\Missing404Exception: {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"accounts","index_uuid":"_na_","index":"accounts"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"accounts","index_uuid":"_na_","index":"accounts"},"status":404} in /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:685
```

#### Steps to Reproduce

See above

#### Context

I'm trying to get search results, including a full-text search of description fields for Accounts, Leads, etc.

#### Your Environment

* SuiteCRM Version used: 8.2.3
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 110.0.5481.77 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MariaDB, PHP 8.0.28, Elastic 7.17.9
* Operating System and version (e.g Ubuntu 16.04): php:8.0-apache-bullseye

**Comment by johnM2401** [comment]
Hey!

Thank you for raising this.

I've given this a try on the most recent version (8.8.0) and this appears to have since been resolved.
I believe this was a PHP8 compatability issue.
As SuiteCRM8 has had numerous PHP8 compatability patches since 8.2.3, it now fully supports up to PHP8.3, resolving this issue.

See gif:
![Image](https://github.com/user-attachments/assets/651365c1-3ed1-4f43-a9b1-7b4cde27432e)

I'm going to close this issue off now, but please don't hesitate to get in touch if you're still experiencing this issue. (or any others!)

Thank you for your contribution to the project!
