### ISSUE TITLE
 Unable to save selected template in campaign

### ISSUE THREAD

**Issue by jlavsund** [salesagility/SuiteCRM-Core#229]
When I try to save the selected template in the campaign wizard I get this error in the browser console.

EmailTemplate.js:69 Uncaught TypeError: window.parent.$ is not a function
at save (EmailTemplate.js:69:15)
at EmailTemplateController (EmailTemplate.js:77:55)
at HTMLInputElement.onclick (index.php?return_module=Campaigns&campaign_id=1c129887-849e-9e82-7c3a-64030d550782&return_action=WizardNewsLetter&return_id=1c129887-849e-9e82-7c3a-64030d550782&module=Campaigns&action=WizardMarketing:959:116)
save @ EmailTemplate.js:69
EmailTemplateController @ EmailTemplate.js:77
onclick @ index.php?return_module=Campaigns&campaign_id=1c129887-849e-9e82-7c3a-64030d550782&return_action=WizardNewsLetter&return_id=1c129887-849e-9e82-7c3a-64030d550782&module=Campaigns&action=WizardMarketing:959

I´m using:
SuiteCRM 8.2.4 on an Ubuntu 20.04.5 server with MariaDB 10.3.38 and PHP 7.4.3. and Chrome 110.0.5481.178 on Windows 11.

**Comment by pgorod** [comment]
Perhaps this is the same issue as #186?

Please try this fix here, if applicable:
https://github.com/salesagility/SuiteCRM-Core/issues/186#issuecomment-1471852860

If it is the same, then this issue here can be closed as a duplicate.

**Comment by Zahid-Abbas-Ali-Baig** [comment]
I have resolved the issue in **/public/legacy/modules/EmailTemplates/EmailTemplate.js** 

- Replace the **window.parent.$('.ui-dialog-content:visible').dialog('close');** with $('.ui-dialog-content:visible').dialog('close'); on line number **330**
- Replace the **window.parent.$('.ui-dialog-content:visible').dialog('close');** with $('.ui-dialog-content:visible').dialog('close'); on line number **308**

By doing this it would be fixed @pgorod

**Comment by markbond1007** [comment]
@pgorod 
I can confirm that under Suite 8.8 doing a search/replace for window.parent.$( with $(  in public/legacy/modules/EmailTemplates/EmailTemplates.js fixes this issue.

Kind regards

Mark
