### ISSUE TITLE
Elasticsearch fails for modules with zero items

### ISSUE THREAD

**Issue by sweettbug3** [salesagility/SuiteCRM-Core#232]
When using Elasticsearch, I get an exception and no search results if modules that are searchable do not have any items yet.  

#### Issue

The following error is found when search is used when there are no items in one of the modules indexed.  

```
 Wed Mar 15 18:49:34 2023 [169][1][FATAL] [ERROR] [SearchThrowableHandler] An unknown error has occurred while performing the search.
Wed Mar 15 18:49:34 2023 [169][1][FATAL] [ERROR] [SearchThrowableHandler] Elasticsearch\Common\Exceptions\Missing404Exception: {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [notes]","resource.type":"index_or_alias","resource.id":"notes","index_uuid":"_na_","index":"notes"}],"type":"index_not_found_exception","reason":"no such index [notes]","resource.type":"index_or_alias","resource.id":"notes","index_uuid":"_na_","index":"notes"},"status":404} in /bitnami/suitecrm/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:685
Stack trace:
#0 /bitnami/suitecrm/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(333): Elasticsearch\Connections\Connection->process4xxError()
#1 /bitnami/suitecrm/vendor/react/promise/src/FulfilledPromise.php(28): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}()
#2 /bitnami/suitecrm/vendor/ezimuel/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then()
#3 /bitnami/suitecrm/vendor/ezimuel/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then()
#4 /bitnami/suitecrm/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(345): GuzzleHttp\Ring\Core::proxy()
#5 /bitnami/suitecrm/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(241): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}()
#6 /bitnami/suitecrm/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(110): Elasticsearch\Connections\Connection->performRequest()
#7 /bitnami/suitecrm/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(1929): Elasticsearch\Transport->performRequest()
#8 /bitnami/suitecrm/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(1353): Elasticsearch\Client->performRequest()
#9 /bitnami/suitecrm/public/legacy/lib/Search/ElasticSearch/ElasticSearchEngine.php(160): Elasticsearch\Client->search()
#10 /bitnami/suitecrm/public/legacy/lib/Search/ElasticSearch/ElasticSearchEngine.php(80): SuiteCRM\Search\ElasticSearch\ElasticSearchEngine->runElasticSearch()
#11 /bitnami/suitecrm/public/legacy/lib/Search/SearchEngine.php(77): SuiteCRM\Search\ElasticSearch\ElasticSearchEngine->search()
#12 /bitnami/suitecrm/public/legacy/lib/Search/SearchWrapper.php(88): SuiteCRM\Search\SearchEngine->searchAndDisplay()
#13 /bitnami/suitecrm/public/legacy/modules/Home/Search.php(50): SuiteCRM\Search\SearchWrapper::searchAndDisplay()
#14 /bitnami/suitecrm/public/legacy/modules/Home/UnifiedSearch.php(41): require_once('...')
#15 /bitnami/suitecrm/public/legacy/include/MVC/View/SugarView.php(799): include_once('...')
#16 /bitnami/suitecrm/public/legacy/include/MVC/View/views/view.classic.php(72): SugarView->includeClassicFile()
#17 /bitnami/suitecrm/public/legacy/include/MVC/View/SugarView.php(210): ViewClassic->display()
#18 /bitnami/suitecrm/public/legacy/include/MVC/Controller/SugarController.php(432): SugarView->process()
#19 /bitnami/suitecrm/public/legacy/include/MVC/Controller/SugarController.php(363): SugarController->processView()
#20 /bitnami/suitecrm/public/legacy/include/MVC/SugarApplication.php(101): SugarController->execute()
#21 /bitnami/suitecrm/public/legacy/index.php(52): SugarApplication->execute()
#22 {main}
Wed Mar 15 18:53:00 2023 [228][1][FATAL] Failed to retrieve ElasticSearch options 
```
#### Expected Behavior

Search should work, even if some modules have no data.
It appears that when we connect to elasticsearch we should either: 

1. fail gracefully if the index doesnt exist yet (perhaps because there is nothing to index)
2. we should add an empty index to elasticsearch when we first connect, if it doesnt exist
3. 
#### Actual Behavior

See above from suitecrm.log

#### Possible Fix

Create empty indexes if no index is found when we first configure elasticsearch as our search engine.

#### Steps to Reproduce

1. Download and use bitnami's suitecrm 8.2.4 w/appropriate database
2. Only add data to Accounts module
4. Download and start elasticsearch instance
5. Using admin panel configure suitecrm to use elasticsearch
6. Search for an item in the Accounts module (this will fail and you will see 404 no index error message)

#### Context

It is a poor assumption to assume that everyone using suitecrm will use every module, workaround is to add dummy data for each module or remove modules from search that are not populated.

#### Your Environment

* SuiteCRM Version used: 8.2.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 110.0.5481.177 (Official Build) (x86_64)
* Environment name and version (e.g. MySQL, PHP 7): mariadb, php 8, elasticsearch 7.17.7
* Operating System and version (e.g Ubuntu 16.04): using bitnami docker image bitnami/suitecrm:8 which is Debian-11

**Comment by johnM2401** [comment]
Hey!

I've given this a try locally on 8.8.0, and this appears to now be working well.

I believe this may have been resolved by the numerous PHP8 support fixes that have been done since 8.2.4

See gif:

![Image](https://github.com/user-attachments/assets/bfd638f7-4867-4fcc-9729-de32a1ac60d7)

In this gif I do a full re-index.
Campaigns has 0 records, and successfully returns as such
I can then search on the Campaigns Module and Globally without issue.


<br>

I'm going to close this issue off for now.
However, please don't hesitate to get in touch if this issue is still occurring for you on recent versions of SuiteCRM.
(Or if I have perhaps misunderstood your issue)

Thank you for your contribution to the project!
