### ISSUE TITLE
Unable to merge Contact on SuiteCRM 8.2.4

### ISSUE THREAD

**Issue by vladaman** [salesagility/SuiteCRM-Core#270]
#### Issue
There is an issue with SuiteCRM where an error 500 is encountered while attempting to merge a contact. The API of SuiteCRM returns this error. Please find the log report provided below.

#### Actual Behavior
```
[Wed May 31 09:48:34.495564 2023] [php:error] [pid 489055] [client 176.74.148.1:39104] PHP Fatal error:  Uncaught TypeError: strlen(): Argument #1 ($str) must be of type string, array given in /var/www/crm/SuiteCRM-8.2.4/public/legacy/include/database/DBManager.php:2085
Stack trace:
#0 /var/www/crm/SuiteCRM-8.2.4/public/legacy/include/database/DBManager.php(596): DBManager->updateSQL()
#1 /var/www/crm/SuiteCRM-8.2.4/public/legacy/data/SugarBean.php(2484): DBManager->update()
#2 /var/www/crm/SuiteCRM-8.2.4/public/legacy/include/SugarObjects/templates/person/Person.php(210): SugarBean->save()
#3 /var/www/crm/SuiteCRM-8.2.4/public/legacy/modules/MergeRecords/SaveMerge.php(113): Person->save()
#4 /var/www/crm/SuiteCRM-8.2.4/public/legacy/include/MVC/View/SugarView.php(799): include_once('...')
#5 /var/www/crm/SuiteCRM-8.2.4/public/legacy/include/MVC/View/views/view.classic.php(72): SugarView->includeClassicFile()
#6 /var/www/crm/SuiteCRM-8.2.4/public/legacy/include/MVC/View/SugarView.php(210): ViewClassic->display()
#7 /var/www/crm/SuiteCRM-8.2.4/public/legacy/include/MVC/Controller/SugarController.php(432): SugarView->process()
#8 /var/www/crm/SuiteCRM-8.2.4/public/legacy/include/MVC/Controller/SugarController.php(363): SugarController->processView()
#9 /var/www/crm/SuiteCRM-8.2.4/public/legacy/include/MVC/SugarApplication.php(101): SugarController->execute()
#10 /var/www/crm/SuiteCRM-8.2.4/public/legacy/index.php(52): SugarApplication->execute()
#11 {main}
  thrown in /var/www/crm/SuiteCRM-8.2.4/public/legacy/include/database/DBManager.php on line 2085, referer: https://crm/legacy/index.php
```

#### Possible Fix
Issue is here:
https://github.com/salesagility/SuiteCRM-Core/blob/1f949f1ac2b7fe82f3c2c6071f842b804ba91929/public/legacy/include/database/DBManager.php#L2082

```php
// $val is an array [0] => ""

print_r($fieldDef); // snows following:
Array ( [name] => lawful_basis [vname] => LBL_LAWFUL_BASIS [type] => multienum [massupdate] => 1 [no_default] => [comments] => [inline_edit] => 1 [reportable] => 1 [merge_filter] => enabled [len] => 100 [size] => 20 [options] => lawful_basis_dom [audited] => 1 [importable] => 1 ) Array ( [0] => )
```

```php
// Add Array Check
if (!is_array($val) && strlen($val) == 0) {
   if (isset($fieldDef['default']) && strlen($fieldDef['default']) > 0) {
      $val = $fieldDef['default'];
  } else {
    $val = null;
  }
}
```

#### Steps to Reproduce
1. Merge any Contact

#### Your Environment

* SuiteCRM Version used: 8.2.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Version 1.51.118 Chromium: 113.0.5672.126 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): 8.1.2-1ubuntu2.11
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 22.04

**Comment by johnM2401** [comment]
Hey!

Thank you for raising this @vladaman !

I've given this a try on the latest version, 8.8.0, and this appears to have since been resolved.

See gif:
![Image](https://github.com/user-attachments/assets/18d0e32b-4f99-4420-9186-8364daef1075)

I'm going to close this issue off for now, but if you're still seeing this issue on more recent versions of SuiteCRM8 then please don't hesitate to get in touch and I'd be happy to investigate further.

Thank you again for your contributions!
