### ISSUE TITLE
yarn run build:core Maximum call stack size exceeded

### ISSUE THREAD

**Issue by dwaltsch** [salesagility/SuiteCRM-Core#306]
#### Issue
When running the following command in my SuiteCRM 8.32 dev environment I encounter an Maximum call stack size exceeded error
````
yarn run build:core
````

#### Expected Behavior
The following commands from [here](https://docs.suitecrm.com/8.x/developer/installation-guide/front-end-installation-guide/) should execute and end up displaying the site

#### Actual Behavior
````
Building Angular Package

------------------------------------------------------------------------------
Building entry point 'core'
------------------------------------------------------------------------------
✖ Compiling with Angular in legacy View Engine compilation mode.
Maximum call stack size exceeded
verbose 28.625965246 Error: Command failed with exit code 1.
    at ProcessTermError.ExtendableBuiltin (/usr/share/yarn/lib/cli.js:721:66)
    at ProcessTermError.MessageError (/usr/share/yarn/lib/cli.js:750:123)
    at new ProcessTermError (/usr/share/yarn/lib/cli.js:790:113)
    at /usr/share/yarn/lib/cli.js:34406:30
    at Generator.throw (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:310:30)
    at /usr/share/yarn/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@SuiteCRM8:/var/www/html/suitev8dev# 
````

#### Your Environment`

````
root@SuiteCRM8:/var/www/html/suitev8dev# ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.1.0
Node: 14.20.1
Package Manager: yarn 1.22.19
OS: linux x64

Angular: 12.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.18
@angular-devkit/build-angular   12.2.18
@angular-devkit/core            12.1.0
@angular-devkit/schematics      12.1.0
@angular/cdk                    12.2.13
@schematics/angular             12.1.0
ng-packagr                      12.2.7
rxjs                            6.6.7
typescript                      4.3.5
webpack                         5.88.2
    
root@SuiteCRM8:/var/www/html/suitev8dev# 
````
yarn generates no error log file for some reason I have tried deleting and reinstalling node_modules multiple times as well as switching to 8.30

**Comment by johnM2401** [comment]
Hey!

Thank you for getting in touch!

I've tried to replicate this issue, but im afraid i'm not able yet.

I've tried running the ```yarn run build:core``` (and other yarn run commands) in the 8.3.1-dev package, and these appear to complete.


From the info you've given, you seem to be within the compatibility matrix, but it might be worth double-checking:
https://docs.suitecrm.com/8.x/admin/compatibility-matrix/

<br>

When testing, I used the 8.3.1-dev package found here:
https://github.com/salesagility/SuiteCRM-Core/releases/tag/v8.3.1

Was this the one you used?
Or did you get this installation from elsewhere?
(ie: Cloned from github / sourceforge / etc)

<br>

Additionally, at which point are you running these commands?
I don't *believe* you would need to run these commands when installing using the prebuilt packages above.
It might help to know how far along in the process you are

Thanks!

**Comment by dwaltsch** [comment]
I was running [SuiteCRM-8.3.1-dev.zip](https://github.com/salesagility/SuiteCRM-Core/releases/download/v8.3.1/SuiteCRM-8.3.1-dev.zip) as well as [SuiteCRM-8.3.1-dev.zip](https://github.com/salesagility/SuiteCRM-Core/releases/download/v8.3.1/SuiteCRM-8.3.1-dev.zip) where as far as the documentation states you need to run the commands to build the interface as well as when you want to add your package [SuitCRM Docs](https://docs.suitecrm.com/8.x/developer/extensions/frontend/fe-extensions-setup/) . I'll try to completely wipe the system know at this point i believe its some weird incompatibility issue
