### ISSUE TITLE
Mass Update in Calls and Meetings list view not working

### ISSUE THREAD

**Issue by BastianHammer** [salesagility/SuiteCRM-Core#371]
The mass update feature in the calls and meetings (maybe others as well) list view isn't working.

#### Issue

There is no cancel / submit button, as it is being shown in Leads, Accounts, etc.

#### Expected Behavior

A complete form with the mass-updateable fields + the submit button should be rendered.
![image](https://github.com/salesagility/SuiteCRM-Core/assets/96183835/19d1c8f2-5741-48a7-bf6a-809272e6b6c7)

#### Actual Behavior

![image](https://github.com/salesagility/SuiteCRM-Core/assets/96183835/92cfd64b-bd59-4270-ab0a-49b42f07890f)

`
node_modules_angular_core_fesm2015_core_js-es2015.e67882692b6d3d658f6b.js:1 ERROR TypeError: Cannot read properties of undefined (reading 'fields')
    at dist_core___ivy_ngcc___fesm2015_core_js-_0b011-es2015.ca6d992010619201adb7.js:51:216314
    at Array.forEach (<anonymous>)
    at e.getFields (dist_core___ivy_ngcc___fesm2015_core_js-_0b011-es2015.ca6d992010619201adb7.js:51:216289)
    at Zs (dist_core___ivy_ngcc___fesm2015_core_js-_0b011-es2015.ca6d992010619201adb7.js:1:222913)
    at As (node_modules_angular_core_fesm2015_core_js-es2015.e67882692b6d3d658f6b.js:1:71106)
    at Os (node_modules_angular_core_fesm2015_core_js-es2015.e67882692b6d3d658f6b.js:1:69732)
    at node_modules_angular_core_fesm2015_core_js-es2015.e67882692b6d3d658f6b.js:1:70159
    at Os (node_modules_angular_core_fesm2015_core_js-es2015.e67882692b6d3d658f6b.js:1:70184)
    at eu (node_modules_angular_core_fesm2015_core_js-es2015.e67882692b6d3d658f6b.js:1:77013)
    at node_modules_angular_core_fesm2015_core_js-es2015.e67882692b6d3d658f6b.js:1:70594
`

#### Steps to Reproduce

1. Install CRM, import demo Data
2. Go to calls or meetings
3. Select some and click mass update

#### Context

low - medium priority, it's still possible to work via imports.
Maybe there are other views affected as well.

#### Your Environment

* SuiteCRM Version used: 8.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chromium 
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 8.1
* Operating System and version (e.g Ubuntu 16.04): Ubuntu Server 23.04

**Comment by lukeonorato** [comment]
i got a similar bug, in my case, the following bulk actions (mass update, add to target list) using "all selected" option, for any module, i got a message in CRM front "Selecting all records is not available for this action. Please select individual records." But without "fatal" in log, only this => 
![image](https://github.com/salesagility/SuiteCRM-Core/assets/126571261/f9b0a9aa-c353-4399-baf8-b6d909169698)

**Comment by wildbuzz666** [comment]
Same error in Calls and Meeting module
![Schermata 2024-01-29 alle 11 18 17](https://github.com/salesagility/SuiteCRM-Core/assets/62009772/891789cb-6ae1-4180-a889-5dc03286a9ee)
![Schermata 2024-01-29 alle 11 20 29](https://github.com/salesagility/SuiteCRM-Core/assets/62009772/f6bbfea4-b9f7-4b3f-8a70-a90890c08e9e)

**Comment by johnM2401** [comment]
Hey all!

Thank you for raising and further diagnosing this issue.

I believe this was fixed in 8.6.2 with the PR: https://github.com/salesagility/SuiteCRM-Core/pull/518

![Image](https://github.com/user-attachments/assets/d45b5439-0988-496c-8c92-39e855050350)

![Image](https://github.com/user-attachments/assets/83248adf-656a-4f9f-9be8-504fa8415164)

<br>

I'm going to close this issue off for now, but if anyone is still experiencing this issue in more recent versions of SuiteCRM8, please don't hesitate to get in touch!

Thank you all again for your contributions!
