### ISSUE TITLE
Suite 8.4 - Create new project - Console:  Cannot read properties of null (reading 'getFullYear')

### ISSUE THREAD

**Issue by BastianHammer** [salesagility/SuiteCRM-Core#376]
When creating a new project in Suite 8.4 there is an error thrown in the browser console.

#### Issue

Error message:
`
sugar_grp_project.js:118 Uncaught TypeError: Cannot read properties of null (reading 'getFullYear')
    at SugarWidgetSchedulerAttendees.init (sugar_grp_project.js:118:616)
    at new SugarWidgetSchedulerAttendees (sugar_grp_project.js:112:112)
    at SugarWidgetScheduler.display (sugar_grp_project.js:100:94)
    at SugarWidgetScheduler.load (sugar_grp_project.js:90:90)
    at SugarContainer.start (sugar_grp_project.js:6:106)
    at YAHOO.util.YUILoader.onSuccess (index.php?return_module=Project&return_action=DetailView&module=Project&action=EditView:511:27)
    at YAHOO.util.YUILoader.loadNext (sugar_grp1.js?v=WF72x91slYsllX0_Sa56cw:779:30350)
    at YAHOO.util.YUILoader.donext (sugar_grp1.js?v=WF72x91slYsllX0_Sa56cw:779:29252)
    at c (sugar_grp1.js?v=WF72x91slYsllX0_Sa56cw:779:7851)
    at f (sugar_grp1.js?v=WF72x91slYsllX0_Sa56cw:779:8607)
`
![image](https://github.com/salesagility/SuiteCRM-Core/assets/96183835/a4cf4f1f-7ec8-4333-8133-393eb25fe0f8)

Still - it's possible to save the project without any issues.

#### Expected Behavior

No major errors on the console

#### Steps to Reproduce

1. Install SuiteCRM 8.4
2. Click on Create Project

#### Context

Seems to be fine actually - or at least I am able to save the project.
Probably rather a low priority.

#### Your Environment

* SuiteCRM Version used: 8.4.0
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chromium Version 118.0.5993.88
* Environment name and version (e.g. MySQL, PHP 7): 8.1
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 23.04 Server

**Comment by Stejcek** [comment]
I confirm the same behavior for SuiteCRM 8.4.0. 

****Your Environment

- SuiteCRM Version used: 8.4.0
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): 121.0.6167.85 (Oficiální sestavení) (64bitový)
- Environment name and version (e.g. MySQL, PHP 7): 8.1
- Operating System and version (e.g Ubuntu 16.04): Ubuntu 20.04 Server
