### ISSUE TITLE
Special character in database password creates issues

### ISSUE THREAD

**Issue by jschoder-ryl** [salesagility/SuiteCRM-Core#553]
### Issue

I just ran a test migration of our 7.14 instance to 8.7.0 and get an error since our database password contains special characters (pure ascii characters in the range %21 to %7e). Changing the password to remove any character apart from 0-9a-zA-Z "fixes" the problem temporarily but this can't be a long term solution. Here is the specific error message: 

```
PHP Fatal error:  Uncaught Symfony\\Component\\DependencyInjection\\Exception\\ParameterNotFoundException: You have requested a non-existent parameter "xxxxxxxxxxx". in /var/www/suitecrm/cache/prod/Container91EHOYK/App_KernelProdContainer.php:2089
Stack trace:
#0 /var/www/suitecrm/vendor/symfony/dependency-injection/EnvVarProcessor.php(343): Container91EHOYK\\App_KernelProdContainer->getParameter()
#1 [internal function]: Symfony\\Component\\DependencyInjection\\EnvVarProcessor->Symfony\\Component\\DependencyInjection\\{closure}()
#2 /var/www/suitecrm/vendor/symfony/dependency-injection/EnvVarProcessor.php(335): preg_replace_callback()
#3 /var/www/suitecrm/vendor/symfony/dependency-injection/Container.php(382): Symfony\\Component\\DependencyInjection\\EnvVarProcessor->getEnv()
#4 /var/www/suitecrm/cache/prod/Container91EHOYK/App_KernelProdContainer.php(607): Symfony\\Component\\DependencyInjection\\Container->getEnv()
#5 /var/www/suitecrm/cache/prod/Container91EHOYK/App_KernelProdContainer.php(676): Container91EHOYK\\App_KernelProdContainer::getDoctrine_Dbal_DefaultConnectionService()
#6 /var/www/suitecrm/cache/prod/Container91EHOYK/App_KernelProdContainer.php(618): Container91EHOYK\\App_KernelProdContainer::getDoctrine_Orm_DefaultEntityManagerService()
#7 /var/www/suitecrm/vendor/symfony/var-exporter/Internal/LazyObjectState.php(100): Container91EHOYK\\App_KernelProdContainer::Container91EHOYK\\{closure}()
#8 /var/www/suitecrm/vendor/symfony/var-exporter/LazyGhostTrait.php(178): Symfony\\Component\\VarExporter\\Internal\\LazyObjectState->initialize()
#9 /var/www/suitecrm/vendor/doctrine/orm/src/EntityManager.php(207): Container91EHOYK\\EntityManagerGhost6410e2e->__get()
#10 /var/www/suitecrm/vendor/doctrine/doctrine-bundle/src/CacheWarmer/DoctrineMetadataCacheWarmer.php(42): Doctrine\\ORM\\EntityManager->getMetadataFactory()
#11 /var/www/suitecrm/vendor/symfony/framework-bundle/CacheWarmer/AbstractPhpFileCacheWarmer.php(47): Doctrine\\Bundle\\DoctrineBundle\\CacheWarmer\\DoctrineMetadataCacheWarmer->doWarmUp()
#12 /var/www/suitecrm/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php(108): Symfony\\Bundle\\FrameworkBundle\\CacheWarmer\\AbstractPhpFileCacheWarmer->warmUp()
#13 /var/www/suitecrm/vendor/symfony/http-kernel/Kernel.php(545): Symfony\\Component\\HttpKernel\\CacheWarmer\\CacheWarmerAggregate->warmUp()
#14 /var/www/suitecrm/core/backend/Kernel.php(112): Symfony\\Component\\HttpKernel\\Kernel->initializeContainer()
#15 /var/www/suitecrm/vendor/autoload_runtime.php(37): App\\Kernel->init()
#16 /var/www/suitecrm/public/index.php(5): require_once('...')
#17 {main}
  thrown in /var/www/suitecrm/cache/prod/Container91EHOYK/App_KernelProdContainer.php on line 2089
```

### Steps to Reproduce the Issue

```bash
1. Create a 7.14 instance
2. Set the password to use a special character (e.g. $)
3. Perform the migration to 8.7
4. Try to open the web site

Temporary fix and confirmation that the handling of special characters is the issue
1. Change the password to using only numbers, lower and uppercase characters
2. Update .env.local and public/legacy/config.php with the new password
3. Open the web site again
```

### Version

8.7.0

### What browser are you currently using?

Firefox

### Environment Information

PHP 8.2.24, MySQL 8.0.39

### Operating System and Version

Tuxedo 3 (Ubuntu Clone)

**Comment by clemente-raposo** [comment]
Hi @jschoder-ryl,

We've pushed a fix for this issue in version 8.8.0.

Please check the commit linked above.

Thank you for your contribution to the SuiteCRM project!
