### ISSUE TITLE
After an upgrade error in cron / Reminder.php with null

### ISSUE THREAD

**Issue by vladaman** [salesagility/SuiteCRM-Core#588]
### Issue

After an upgrade to 8.7.1 I get the following error when executing cron from the command line:

```
sudo -u www-data php cron.php 

PHP Fatal error:  Uncaught Error: Call to a member function modify() on null in /var/www/crm/public/legacy/modules/Reminders/Reminder.php:266
Stack trace:
#0 /var/www/crm/public/legacy/modules/Reminders/Reminder.php(216): Reminder::getUnsentEmailReminders()
salesagility/SuiteCRM#1 /var/www/crm/public/legacy/modules/Activities/EmailReminder.php(98): Reminder::sendEmailReminders()
salesagility/SuiteCRM#2 /var/www/crm/public/legacy/modules/Schedulers/_AddJobsHere.php(435): EmailReminder->process()
salesagility/SuiteCRM#3 /var/www/crm/public/legacy/modules/SchedulersJobs/SchedulersJob.php(529): sendEmailReminders()
salesagility/SuiteCRM#4 /var/www/crm/public/legacy/include/SugarQueue/SugarCronJobs.php(191): SchedulersJob->runJob()
salesagility/SuiteCRM#5 /var/www/crm/public/legacy/include/SugarQueue/SugarCronJobs.php(233): SugarCronJobs->executeJob()
salesagility/SuiteCRM#6 /var/www/crm/public/legacy/cron.php(100): SugarCronJobs->runCycle()
salesagility/SuiteCRM#7 {main}
  thrown in /var/www/crm/public/legacy/modules/Reminders/Reminder.php on line 266
```

Related to this line:
https://github.com/salesagility/SuiteCRM/blob/e572230abd0dad205b24a96acce72590b20bf69d/modules/Reminders/Reminder.php#L266

### Steps to Reproduce the Issue

```bash
1.
2.
3.
...
```

### Version

8.7.1

### What browser are you currently using?

Chrome

### Environment Information

Mysql

### Operating System and Version

Ubuntu

**Comment by johnM2401** [comment]
Hey!
Thank you for being in touch.
I've given this a try locally but have not yet been able to replicate, I'm afraid

Could you share some more info on this scenario so I can try to closer match your setup/steps?

ie:
- Does this happen for every Call/Meeting, or just specific ones?
- On the Meetings/Calls with pending Reminder Emails, do the invitees have valid Email addresses?
- On the Meetings/Calls with pending Reminder Emails, do the invitees have non-UTC timezones or Custom Date/time Formats?
- Do you see anything in the SuiteCRM Error logs for this? (ie: /public/legacy/SuiteCRM.log or /logs/prod/prod.log)
- Which PHP Version are you using when running cron?
- Did you have any issues during upgrade? (ie: When running both upgrade and upgrade-finalize commands?)

Thank you again!
