### ISSUE TITLE
Workflow Editor: Calculate fields not populating

### ISSUE THREAD

**Issue by erikcarlsonnteligen** [salesagility/SuiteCRM-Core#93]
When trying to create a new workflow, when the calculate fields is selected in the actions dropdown the choices do not populate in the panel

#### Issue
When creating a new workflow, the ability to do a calculated workflow is not present. When logged in as an admin and navigate to the creation of a new workflow.  In the actions panel, the select action dropdown has 4 choices.  Each choice should populate new fields in the panel to fill out. Create Record, Modify Record, and send email work as expected. Calculate fields does not populate anything.

Calculate fields not working
![image](https://user-images.githubusercontent.com/61192727/167898404-51971bf3-8d81-4c9a-a163-1a043f0a2525.png)

Send Email working
![image](https://user-images.githubusercontent.com/61192727/167898590-5bd67737-170c-4272-bef0-3ea2948bd03f.png)

#### Expected Behavior
Per the user manual, when Calculate fields is selected there should be frields to populate like the picture below.

![image](https://user-images.githubusercontent.com/61192727/167898814-471f0d71-eb19-4339-897f-5b8b8340cb51.png)

#### Actual Behavior
The calculate fields do not populate

#### Steps to Reproduce
1. log in as administrator
2.  go to admin menu
3. go to workflow manager
4. click new workflow
5. populate a name "test"
6.  Choose workflow module (Opportunities)
7.  Expand Actions Panel
8. Choose Calculate Fields In Select Action Dropdown
9. Nothing Happens
10. Choose another option in select action dropdown
11. Fields for that dropdown are populated

#### Context
Can create a custom calculated workflow

#### Your Environment
* SuiteCRM Version used: Version 8.0.0
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome  101.0.4951.54
* Environment name and version (e.g. MySQL, PHP 7): MySQL = 8.0.29-0ubuntu0.20.04.3 for Linux on x86_64,  PHP 8.0
* Operating System and version (e.g Ubuntu 16.04):  Ubuntu 20.04.4 LTS

**Comment by pgorod** [comment]
Do you have any messages in your `php_errors.log` at the time of using that screen?

Can you try it with PHP 7.3 or 7.4 to see if the error is only with PHP 8?

**Comment by erikcarlsonnteligen** [comment]
Below is the error I found when executing the steps above.  I cannot try with a different version of PHP at this time as the system is under heavy use.

[Thu May 12 09:50:56.270729 2022] [proxy_fcgi:error] [pid 1885826] [client 192.168.1.X:64632] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, bool given in /var/www/suitecrm/public/legacy/modules/AOW_Actions/actions/actionComputeField.php:452\nStack trace:\n#0 /var/www/suitecrm/public/legacy/modules/AOW_WorkFlow/controller.php(558): actionComputeField->edit_display()\n#1 /var/www/suitecrm/public/legacy/include/MVC/Controller/SugarController.php(522): AOW_WorkFlowController->action_getAction()\n#2 /var/www/suitecrm/public/legacy/include/MVC/Controller/SugarController.php(491): SugarController->do_action()\n#3 /var/www/suitecrm/public/legacy/include/MVC/Controller/SugarController.php(465): SugarController->handle_action()\n#4 /var/www/suitecrm/public/legacy/include/MVC/Controller/SugarController.php(361): SugarController->process()\n#5 /var/www/suitecrm/public/legacy/include/MVC/SugarApplication.php(101): SugarController->execute()\n#6 /var/www/suitecrm/public/legacy/index.php(52): SugarApplication->execute()\n#7 {main}\n  thrown in /va...', referer: https://suitecrm8.hq.com/legacy/index.php?return_module=AOW_WorkFlow&return_action=DetailView&module=AOW_WorkFlow&action=EditView

**Comment by johnM2401** [comment]
Hey!

Thank you for raising this, and for your contribution to the project!

It looks like this was resolved as of 8.4.2, with this PR: https://github.com/salesagility/SuiteCRM/pull/10122

So i'm going to close this issue off for now.

However, if you are still experiencing this issue in the most recent versions (or any other issues), please get in touch!

Thank you again!
